// ==UserScript==
// @name         YouTube AI Score — DOM only
// @namespace    https://github.com/darocaecobr/lexico-filter
// @author       darocaecobr
// @homepageURL  https://github.com/darocaecobr/lexico-filter
// @supportURL   https://github.com/darocaecobr/lexico-filter/issues
// @version      0.6.2
// @description  Adds local heuristic AI/AUTOMATION/CLICKBAIT scores to YouTube video cards using only DOM metadata.
// @match        https://www.youtube.com/*
// @updateURL    https://raw.githubusercontent.com/darocaecobr/lexico-filter/refs/heads/main/yt-filter.js
// @downloadURL  https://raw.githubusercontent.com/darocaecobr/lexico-filter/refs/heads/main/yt-filter.js
// @grant        GM_addStyle
// @grant        GM_registerMenuCommand
// @run-at       document-idle
// ==/UserScript==

(() => {
    "use strict";

    const VERSION = "0.6.2";
    const STORAGE_KEY = "yt-ai-score-cache-v2";
    const SETTINGS_KEY = "yt-ai-score-settings-v2";
    const LEXICON_CACHE_KEY = "yt-ai-score-lexicon-v1";
    const RESCAN_MS = 2500;

    const DEFAULTS = {
        showAI: true,
        showAutomation: true,
        showClickbait: true,
        minimumScoreToShow: 1.00,
        minimumAutomationToShow: 1.00,
        minimumClickbaitToShow: 1.00,
        cacheMaxEntries: 2000,
        // Faixas de cor dos badges
        lowThreshold: 0.20,
        mediumThreshold: 0.50,
        highThreshold: 0.75,
        // Pesos do score de IA
        titleWeight: 0.15,
        titleCap: 0.50,
        channelWeight: 0.10,
        channelCap: 0.20,
        bodyWeight: 0.03,
        bodyCap: 0.15,
        automationPerMatch: 0.25,
        automationBonus: 0.15,
        // Clickbait
        clickbaitPointsNeeded: 3,
        longTitleLen: 100,
        // Léxicos remotos minerados (data/<kind>_br.json via HTTP)
        // Padrão: repo darocaecobr/lexico-filter (raw do GitHub).
        lexiconClickbaitUrl: "https://raw.githubusercontent.com/darocaecobr/lexico-filter/refs/heads/main/data/clickbait_br.json",
        lexiconAiUrl: "https://raw.githubusercontent.com/darocaecobr/lexico-filter/refs/heads/main/data/ai_br.json",
        lexiconAutomationUrl: "https://raw.githubusercontent.com/darocaecobr/lexico-filter/refs/heads/main/data/automation_br.json",
        lexiconAutoUpdate: true,
        remoteWeight: 0.50,
        remoteCap: 0.40,
        aiRemoteWeight: 0.50,
        aiRemoteCap: 0.40,
        autoRemoteWeight: 0.50,
        autoRemoteCap: 0.40,
    };

    const CONFIG = loadSettings();
    const AI_TERMS = [
        "ai generated", "ai-generated", "generated by ai",
        "made with ai", "artificial intelligence",
        "chatgpt", "midjourney", "dall-e", "stable diffusion",
        "sora", "elevenlabs", "synthetic media",
        "ai voice", "ai video", "ai avatar",
        "voz artificial", "gerado por ia", "inteligência artificial",
        "feito com ia", "conteúdo sintético"
    ];

    const AUTOMATION_TERMS = [
        "top 10", "top 5", "top 20",
        "things you didn't know", "things you never knew",
        "you won't believe", "shocking facts", "amazing facts",
        "did you know", "secrets you", "unknown facts",
        "10 coisas que", "você não sabia", "fatos incríveis",
        "curiosidades que"
    ];

    const cache = loadCache();

    function log(...args) {
        console.debug("[YT-AI]", ...args);
    }

    function normalize(text) {
        return String(text || "")
            .normalize("NFKC")
            .replace(/\s+/g, " ")
            .trim();
    }

    function lower(text) {
        return normalize(text).toLocaleLowerCase();
    }

    function loadSettings() {
        try {
            const raw = localStorage.getItem(SETTINGS_KEY);
            const parsed = raw ? JSON.parse(raw) : {};
            const merged = { ...DEFAULTS, ...parsed };

            // Sanitiza thresholds 0..1 e garante ordem low < medium < high.
            for (const key of [
                "minimumScoreToShow", "minimumAutomationToShow",
                "minimumClickbaitToShow", "lowThreshold",
                "mediumThreshold", "highThreshold",
                "titleWeight", "titleCap", "channelWeight",
                "channelCap", "bodyWeight", "bodyCap",
                "automationPerMatch", "automationBonus",
                "remoteWeight", "remoteCap",
                "aiRemoteWeight", "aiRemoteCap",
                "autoRemoteWeight", "autoRemoteCap"
            ]) {
                let value = Number(merged[key]);

                if (!Number.isFinite(value)) {
                    value = DEFAULTS[key];
                }

                merged[key] = Math.max(0, Math.min(1, value));
            }

            merged.clickbaitPointsNeeded = Math.max(
                1,
                Math.min(6, Math.round(Number(merged.clickbaitPointsNeeded) || DEFAULTS.clickbaitPointsNeeded))
            );
            merged.longTitleLen = Math.max(
                40,
                Math.min(200, Math.round(Number(merged.longTitleLen) || DEFAULTS.longTitleLen))
            );
            merged.cacheMaxEntries = Math.max(
                100,
                Math.min(10000, Math.round(Number(merged.cacheMaxEntries) || DEFAULTS.cacheMaxEntries))
            );
            merged.showAI = merged.showAI !== false;
            merged.showAutomation = merged.showAutomation !== false;
            merged.showClickbait = merged.showClickbait !== false;
            merged.lexiconAutoUpdate = merged.lexiconAutoUpdate !== false;

            // URLs dos léxicos remotos (raw do git). Vazias = só embutido.
            // Migra config v0.4 (lexiconUrl único) p/ clickbait.
            if (!merged.lexiconClickbaitUrl && merged.lexiconUrl) {
                merged.lexiconClickbaitUrl = merged.lexiconUrl;
            }
            delete merged.lexiconUrl;

            for (const key of [
                "lexiconClickbaitUrl", "lexiconAiUrl", "lexiconAutomationUrl"
            ]) {
                merged[key] = String(merged[key] || "").trim();

                if (merged[key] && !/^https?:\/\//i.test(merged[key])) {
                    merged[key] = "";
                }
            }

            if (!(merged.lowThreshold < merged.mediumThreshold &&
                merged.mediumThreshold < merged.highThreshold)) {
                merged.lowThreshold = DEFAULTS.lowThreshold;
                merged.mediumThreshold = DEFAULTS.mediumThreshold;
                merged.highThreshold = DEFAULTS.highThreshold;
            }

            return merged;
        } catch {
            return { ...DEFAULTS };
        }
    }

    function saveSettings() {
        try {
            localStorage.setItem(SETTINGS_KEY, JSON.stringify(CONFIG));
        } catch (error) {
            log("settings save failed", error);
        }
    }

    function clearScoreCache() {
        cache.clear();

        try {
            localStorage.removeItem(STORAGE_KEY);
        } catch {
            // Ignore storage errors.
        }
    }

    /*
     * Léxicos remotos: JSON gerado por scripts/mine_br_lexicon.py
     * ({version, kind, phrases: [{t, s}]}) hospedado no git e obtido
     * via HTTP (ex. URL raw.githubusercontent.com). O cache em
     * localStorage garante funcionamento offline; sem URL
     * configurada, cada dimensão usa só o léxico embutido.
     * Fontes das seeds: clickbait (YTClickbait21K/BaitBuster/MVD/
     * BollyBAIT), IA (teses deepfake UNICAMP/UTFPR/UFPR + nomes de
     * ferramentas T2V dos papers VID-AID/GenVideo/GenBuster) e
     * automação (Alliance4Europe "Infinite Slop Machine", YouTube
     * purga 2026 de content farms, Agarwal/SEPS, CollATe).
     */
    const LEXICON_KINDS = ["clickbait", "ai", "automation"];

    const lexicons = {
        clickbait: { phrases: [], version: null, status: "embutido" },
        ai: { phrases: [], version: null, status: "embutido" },
        automation: { phrases: [], version: null, status: "embutido" },
    };

    function lexiconUrlKey(kind) {
        return `lexicon${kind[0].toUpperCase()}${kind.slice(1)}Url`;
    }

    function cleanPhrases(entries) {
        return (entries || [])
            .filter(entry => typeof entry?.t === "string" && entry.t.trim())
            .map(entry => ({
                t: entry.t,
                s: Math.max(0, Math.min(1, Number(entry.s) || 0)),
            }));
    }

    function loadLexiconCache() {
        let parsed = null;

        try {
            const raw = localStorage.getItem(LEXICON_CACHE_KEY);
            parsed = raw ? JSON.parse(raw) : null;
        } catch {
            parsed = null;
        }

        // Migra cache antigo (formato v0.4: {version, phrases}) p/ clickbait.
        if (parsed && Array.isArray(parsed.phrases) && !parsed.clickbait) {
            parsed = { clickbait: parsed };
        }

        for (const kind of LEXICON_KINDS) {
            const cached = parsed?.[kind];

            if (cached && Array.isArray(cached.phrases)) {
                lexicons[kind].phrases = cleanPhrases(cached.phrases);
                lexicons[kind].version = cached.version || null;
                lexicons[kind].status =
                    `cache ${cached.version || "?"} (${lexicons[kind].phrases.length})`;
            }
        }
    }

    function saveLexiconCache() {
        try {
            const payload = {};

            for (const kind of LEXICON_KINDS) {
                payload[kind] = {
                    version: lexicons[kind].version,
                    phrases: lexicons[kind].phrases,
                };
            }

            localStorage.setItem(LEXICON_CACHE_KEY, JSON.stringify(payload));
        } catch {
            // Cache opcional.
        }
    }

    async function fetchOneLexicon(kind) {
        const url = CONFIG[lexiconUrlKey(kind)];

        if (!url) {
            return false;
        }

        const state = lexicons[kind];
        state.status = "baixando…";
        updateLexiconStatus();

        try {
            const response = await fetch(url, { cache: "no-store" });

            if (!response.ok) {
                throw new Error(`HTTP ${response.status}`);
            }

            const payload = await response.json();

            if (!Array.isArray(payload?.phrases)) {
                throw new Error("JSON sem 'phrases'");
            }

            if (payload.kind && payload.kind !== kind) {
                log(`lexicon kind mismatch: esperado ${kind}, veio ${payload.kind}`);
            }

            state.phrases = cleanPhrases(payload.phrases);
            state.version = payload.version || null;
            state.status =
                `remoto ${state.version || "?"} (${state.phrases.length})`;

            return true;
        } catch (error) {
            state.status = `falha: ${error?.message || error}`;
            log(`lexicon ${kind} fetch failed`, error);

            return false;
        } finally {
            updateLexiconStatus();
        }
    }

    async function fetchRemoteLexicons() {
        const results = await Promise.all(
            LEXICON_KINDS.map(kind => fetchOneLexicon(kind))
        );

        if (results.some(Boolean)) {
            saveLexiconCache();
            clearScoreCache();
            scan();
        }

        updateLexiconStatus();
    }

    function matchLexicon(text, kind) {
        const phrases = lexicons[kind]?.phrases;

        if (!phrases?.length) {
            return [];
        }

        const value = lower(text);

        return phrases.filter(entry => {
            if (!entry.t) {
                return false;
            }

            const term = entry.t.toLocaleLowerCase();

            // Frases: substring. Unigramas curtos exigem fronteira
            // de palavra (evita "te"⊂"tech", "ele"⊂"elevenlabs").
            if (term.includes(" ")) {
                return value.includes(term);
            }

            try {
                const esc = term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
                return new RegExp(
                    `(^|[^\\p{L}\\p{N}_])${esc}(?![\\p{L}\\p{N}_])`,
                    "u"
                ).test(value);
            } catch {
                return value.includes(term);
            }
        });
    }

    function updateLexiconStatus() {
        for (const kind of LEXICON_KINDS) {
            document.querySelector(`#yt-ai-lexicon-status-${kind}`)?.replaceChildren(
                document.createTextNode(
                    `${kind}: ${lexicons[kind].status}`
                )
            );
        }
    }

    function loadCache() {
        try {
            const raw = localStorage.getItem(STORAGE_KEY);
            const parsed = raw ? JSON.parse(raw) : {};
            return new Map(Object.entries(parsed));
        } catch {
            return new Map();
        }
    }

    function saveCache() {
        try {
            const entries = [...cache.entries()]
                .slice(-CONFIG.cacheMaxEntries);

            localStorage.setItem(
                STORAGE_KEY,
                JSON.stringify(Object.fromEntries(entries))
            );
        } catch (error) {
            log("cache save failed", error);
        }
    }

    function extractVideoId(card) {
        const anchors = card.querySelectorAll(
            'a[href*="/watch?"], a[href*="/shorts/"]'
        );

        for (const anchor of anchors) {
            try {
                // anchor.href já é absoluto; sem base para não quebrar
                // em origens opacas (ex. file://, origin "null").
                const url = new URL(anchor.href);
                const id =
                    url.searchParams.get("v") ||
                    (/\/shorts\/([^/?#]+)/.exec(url.pathname) || [])[1];

                if (id) {
                    return id;
                }
            } catch {
                // Ignore malformed URLs.
            }
        }

        return null;
    }

    function extractTitle(card) {
        const selectors = [
            "#video-title",
            "yt-formatted-string#video-title",
            "a#video-title",
            "h3 a"
        ];

        for (const selector of selectors) {
            const el = card.querySelector(selector);
            const text = normalize(el?.textContent);

            if (text) {
                return text;
            }
        }

        const link = card.querySelector(
            'a[href*="/watch?"][aria-label], a[href*="/shorts/"][aria-label]'
        );

        return normalize(
            link?.getAttribute("aria-label")
        );
    }

    function extractChannel(card) {
        const selectors = [
            "ytd-channel-name",
            "ytd-channel-name a",
            "#channel-name",
            "a[href^='/@']",
            "a[href^='/channel/']"
        ];

        for (const selector of selectors) {
            const el = card.querySelector(selector);
            const text = normalize(el?.textContent);

            if (text) {
                return text;
            }
        }

        return "";
    }

    function extractMetadata(card) {
        return {
            title: extractTitle(card),
            channel: extractChannel(card),
            ariaText: normalize(card.innerText),
        };
    }

    function findTerms(text, terms) {
        const value = lower(text);

        return terms.filter(
            term => value.includes(term)
        );
    }

    function ratioScore(value, denominator) {
        return Math.max(
            0,
            Math.min(1, value / denominator)
        );
    }

    function calculateClickbait(title) {
        if (!title) {
            return 0;
        }

        let points = 0;

        const exclamations =
            (title.match(/!/g) || []).length;

        const questions =
            (title.match(/\?/g) || []).length;

        if (exclamations >= 2) {
            points++;
        }

        if (questions >= 2) {
            points++;
        }

        if (title.length > CONFIG.longTitleLen) {
            points++;
        }

        if (
            /\b\d+\s+(things|facts|reasons|ways)\b/i.test(title)
        ) {
            points++;
        }

        if (
            /\b\d+\s+(coisas|fatos|motivos|maneiras)\b/i.test(title)
        ) {
            points++;
        }

        if (
            /\b(shocking|incredible|amazing|secret|you won't believe)\b/i
                .test(title)
        ) {
            points++;
        }

        if (
            /\b(chocante|incrível|inacreditável|segredo|você não vai acreditar)\b/i
                .test(title)
        ) {
            points++;
        }

        return Math.min(
            1,
            ratioScore(points, CONFIG.clickbaitPointsNeeded)
        );
    }

    function calculateScores(metadata) {
        const titleAI =
            findTerms(metadata.title, AI_TERMS);

        const channelAI =
            findTerms(metadata.channel, AI_TERMS);

        const bodyAI =
            findTerms(metadata.ariaText, AI_TERMS);

        const automation =
            findTerms(
                `${metadata.title} ${metadata.channel}`,
                AUTOMATION_TERMS
            );

        let aiScore = 0;
        let automationScore = 0;

        /*
         * Importante:
         * isto NÃO é um detector de IA.
         * É apenas uma heurística baseada
         * no texto disponível no DOM.
         */

        if (titleAI.length) {
            aiScore += Math.min(
                CONFIG.titleCap,
                titleAI.length * CONFIG.titleWeight
            );
        }

        if (channelAI.length) {
            aiScore += Math.min(
                CONFIG.channelCap,
                channelAI.length * CONFIG.channelWeight
            );
        }

        if (bodyAI.length) {
            aiScore += Math.min(
                CONFIG.bodyCap,
                bodyAI.length * CONFIG.bodyWeight
            );
        }

        if (automation.length) {
            automationScore = Math.min(
                1,
                automation.length * CONFIG.automationPerMatch
            );

            aiScore +=
                automationScore * CONFIG.automationBonus;
        }

        const haystack =
            `${metadata.title} ${metadata.channel}`;

        const remoteMatches = matchLexicon(haystack, "clickbait");
        const remoteAiMatches = matchLexicon(haystack, "ai");
        const remoteAutoMatches = matchLexicon(haystack, "automation");

        let clickbaitScore =
            calculateClickbait(
                metadata.title
            );

        if (remoteMatches.length) {
            const remoteBonus = Math.min(
                CONFIG.remoteCap,
                remoteMatches.reduce((sum, entry) => sum + entry.s, 0) *
                    CONFIG.remoteWeight
            );

            clickbaitScore = Math.max(
                0,
                Math.min(1, clickbaitScore + remoteBonus)
            );
        }

        if (remoteAiMatches.length) {
            aiScore += Math.min(
                CONFIG.aiRemoteCap,
                remoteAiMatches.reduce((sum, entry) => sum + entry.s, 0) *
                    CONFIG.aiRemoteWeight
            );
        }

        if (remoteAutoMatches.length) {
            automationScore = Math.max(
                0,
                Math.min(
                    1,
                    automationScore + Math.min(
                        CONFIG.autoRemoteCap,
                        remoteAutoMatches.reduce((sum, entry) => sum + entry.s, 0) *
                            CONFIG.autoRemoteWeight
                    )
                )
            );
        }

        aiScore = Math.max(
            0,
            Math.min(1, aiScore)
        );

        return {
            ai: Number(aiScore.toFixed(3)),
            automation: Number(
                automationScore.toFixed(3)
            ),
            clickbait: Number(
                clickbaitScore.toFixed(3)
            ),
            evidence: {
                titleAI,
                channelAI,
                bodyAI,
                automation,
                remote: remoteMatches.map(entry => entry.t),
                remoteAI: remoteAiMatches.map(entry => entry.t),
                remoteAuto: remoteAutoMatches.map(entry => entry.t),
            }
        };
    }

    function scoreClass(score) {
        if (score < CONFIG.lowThreshold) {
            return "yt-ai-low";
        }

        if (score < CONFIG.mediumThreshold) {
            return "yt-ai-medium";
        }

        if (score < CONFIG.highThreshold) {
            return "yt-ai-high";
        }

        return "yt-ai-very-high";
    }

    /*
     * Mapeamento aproximado DOM-only para os 5 tipos do
     * dataset BollyBAIT (Mowar et al.): Misleading, Spam,
     * Exaggerated, False Promises, Curiosity Gap.
     * YTClickbait21K e BaitBuster reforçam que o sinal mais
     * forte é a inconsistência título/thumbnail/conteúdo;
     * sem acesso ao vídeo, aproximamos via léxico do título.
     */
    function classifyClickbaitTypes(title, evidence) {
        const value = lower(title);
        const types = [];

        if (evidence.automation.length) {
            types.push("Misleading");
        }

        if (
            (title.match(/!/g) || []).length >= 2 ||
            /\b(shocking|incredible|amazing|chocante|incrível|inacreditável)\b/i.test(title) ||
            /[A-ZÃÕÇÉÍÓÚÂÊÔ]{6,}/.test(title)
        ) {
            types.push("Exaggerated");
        }

        if (
            /\b\d+\s+(things|facts|reasons|ways|coisas|fatos|motivos|maneiras)\b/i.test(title) ||
            /\b(secret|segredo)\b/i.test(title)
        ) {
            types.push("False Promises");
        }

        if (
            (title.match(/\?/g) || []).length >= 2 ||
            /(you won't believe|você não vai acreditar|você não sabia|things you didn't know)/i.test(title)
        ) {
            types.push("Curiosity Gap");
        }

        if (
            title.length > CONFIG.longTitleLen &&
            (title.match(/!/g) || []).length >= 1 &&
            evidence.bodyAI.length >= 2
        ) {
            types.push("Spam");
        }

        if (!types.length && value) {
            types.push("—");
        }

        return types;
    }

    function buildTooltip(
        videoId,
        metadata,
        scores
    ) {
        const types = classifyClickbaitTypes(
            metadata.title,
            scores.evidence
        );

        const lines = [
            `AI_SCORE: ${scores.ai.toFixed(3)}`,
            `AUTOMATION_SCORE: ${scores.automation.toFixed(3)}`,
            `CLICKBAIT_SCORE: ${scores.clickbait.toFixed(3)}`,
            `TIPOS (BollyBAIT): ${types.join(", ")}`,
            "",
            `video_id: ${videoId}`,
            `title: ${metadata.title}`,
            `channel: ${metadata.channel || "(unknown)"}`
        ];

        if (scores.evidence.titleAI.length) {
            lines.push(
                `IA no título: ${scores.evidence.titleAI.join(", ")}`
            );
        }

        if (scores.evidence.channelAI.length) {
            lines.push(
                `IA no canal: ${scores.evidence.channelAI.join(", ")}`
            );
        }

        if (scores.evidence.automation.length) {
            lines.push(
                `Automação: ${scores.evidence.automation.join(", ")}`
            );
        }

        if (scores.evidence.remote?.length) {
            lines.push(
                `Léxico clickbait: ${scores.evidence.remote.slice(0, 5).join(", ")}`
            );
        }

        if (scores.evidence.remoteAI?.length) {
            lines.push(
                `Léxico IA: ${scores.evidence.remoteAI.slice(0, 5).join(", ")}`
            );
        }

        if (scores.evidence.remoteAuto?.length) {
            lines.push(
                `Léxico automação: ${scores.evidence.remoteAuto.slice(0, 5).join(", ")}`
            );
        }

        lines.push(
            `LEXICOS: click=${lexicons.clickbait.version || "emb"}(${lexicons.clickbait.phrases.length}) ai=${lexicons.ai.version || "emb"}(${lexicons.ai.phrases.length}) auto=${lexicons.automation.version || "emb"}(${lexicons.automation.phrases.length})`
        );

        lines.push(
            "",
            `thresholds: low<${CONFIG.lowThreshold.toFixed(2)} med<${CONFIG.mediumThreshold.toFixed(2)} high<${CONFIG.highThreshold.toFixed(2)} clickPts=${CONFIG.clickbaitPointsNeeded}`,
            "Heurística local baseada apenas nos metadados visíveis."
        );

        return lines.join("\n");
    }

    function createBadge(
        videoId,
        metadata,
        scores
    ) {
        const wrapper =
            document.createElement("div");

        wrapper.className =
            "yt-ai-score-wrapper";

        const items = [];

        if (CONFIG.showAI) {
            items.push([
                "AI",
                scores.ai,
                scoreClass(scores.ai)
            ]);
        }

        if (CONFIG.showAutomation) {
            items.push([
                "AUTOMAÇÃO",
                scores.automation,
                scoreClass(scores.automation)
            ]);
        }

        if (CONFIG.showClickbait) {
            items.push([
                "CLICK",
                scores.clickbait,
                scoreClass(scores.clickbait)
            ]);
        }

        for (const [
            name,
            score,
            cssClass
        ] of items) {
            const badge =
                document.createElement("span");

            badge.className =
                `yt-ai-score ${cssClass}`;

            badge.dataset.scoreType =
                name;

            badge.textContent =
                `${name} ${Math.round(score * 100)}%`;

            badge.title =
                buildTooltip(
                    videoId,
                    metadata,
                    scores
                );

            wrapper.appendChild(badge);
        }

        return wrapper;
    }

    function getCardKey(card) {
        const id =
            extractVideoId(card);

        if (!id) {
            return null;
        }

        const metadata =
            extractMetadata(card);

        return [
            id,
            metadata.title,
            metadata.channel
        ].join("|");
    }

    function render(
        card,
        videoId,
        metadata,
        scores
    ) {
        card
            .querySelector(".yt-ai-score-wrapper")
            ?.remove();

        // Score = probabilidade de ser IA/automação/clickbait.
        // Oculta o card quando ALGUMA dimensão passa do seu teto.
        // Teto em 1.00 = desligado (nenhum score passa de 1).
        const hideAI =
            scores.ai > CONFIG.minimumScoreToShow;
        const hideAuto =
            scores.automation > CONFIG.minimumAutomationToShow;
        const hideClick =
            scores.clickbait > CONFIG.minimumClickbaitToShow;

        if (hideAI || hideAuto || hideClick) {
            scanStats.hidden++;
            card.style.display = "none";
            return;
        }

        // Card passou nos filtros: garante que está visível
        // (pode ter sido ocultado por uma varredura anterior).
        card.style.display = "";

        const wrapper =
            createBadge(
                videoId,
                metadata,
                scores
            );

        const thumbnail =
            card.querySelector(
                "ytd-thumbnail, a#thumbnail, yt-thumbnail-view-model, [class*='thumbnail']"
            );

        if (thumbnail) {
            thumbnail.style.position =
                "relative";

            thumbnail.appendChild(
                wrapper
            );

            return;
        }

        const title =
            card.querySelector(
                "#video-title, h3, ytd-channel-name"
            );

        if (title?.parentElement) {
            title.parentElement.prepend(
                wrapper
            );

            return;
        }

        card.prepend(wrapper);
    }

    function processCard(card) {
        if (!(card instanceof Element)) {
            return;
        }

        const videoId =
            extractVideoId(card);

        if (!videoId) {
            return;
        }

        const metadata =
            extractMetadata(card);

        if (
            !metadata.title &&
            !metadata.channel
        ) {
            return;
        }

        scanStats.evaluated++;

        const key =
            getCardKey(card);

        let scores =
            key
                ? cache.get(key)?.scores
                : null;

        if (!scores) {
            scores =
                calculateScores(
                    metadata
                );

            if (key) {
                cache.set(key, {
                    videoId,
                    metadata,
                    scores,
                    updatedAt: Date.now()
                });

                saveCache();
            }
        }

        render(
            card,
            videoId,
            metadata,
            scores
        );
    }

    function scan(root = document) {
        scanStats.evaluated = 0;
        scanStats.hidden = 0;

        const cards =
            root.querySelectorAll(
                [
                    "ytd-rich-item-renderer",
                    "ytd-video-renderer",
                    "ytd-grid-video-renderer",
                    "ytd-compact-video-renderer",
                    "ytd-playlist-video-renderer",
                    // Shorts (home, busca, trending e player).
                    "ytd-reel-item-renderer",
                    "ytd-reel-video-renderer",
                    "ytm-shorts-lockup-view-model",
                    "ytm-shorts-lockup-view-model-v2"
                ].join(",")
            );

        for (const card of cards) {
            processCard(card);
        }

        updateHiddenStatus();
    }

    // Contadores da última varredura (exibidos no menu).
    const scanStats = { evaluated: 0, hidden: 0 };

    function updateHiddenStatus() {
        document.querySelector("#yt-ai-hidden-status")?.replaceChildren(
            document.createTextNode(
                `${scanStats.hidden} ocultos de ${scanStats.evaluated} avaliados`
            )
        );
    }

    let scanQueued = false;

    function scheduleScan() {
        if (scanQueued) {
            return;
        }

        scanQueued = true;

        requestAnimationFrame(() => {
            scanQueued = false;
            scan();
        });
    }

    const observer =
        new MutationObserver(
            mutations => {
                for (const mutation of mutations) {
                    if (
                        mutation.addedNodes.length > 0
                    ) {
                        scheduleScan();
                        return;
                    }
                }
            }
        );

    function sliderRow(panel, { key, label, min, max, step, percent }) {
        const row = document.createElement("label");
        row.className = "yt-ai-row";

        const format = value => percent
            ? `${Math.round(Number(value) * 100)}%`
            : Number(value).toFixed(2);

        const head = document.createElement("div");
        head.className = "yt-ai-row-head";

        const name = document.createElement("span");
        name.textContent = label;

        const value = document.createElement("span");
        value.className = "yt-ai-val";
        value.textContent = format(CONFIG[key]);

        head.appendChild(name);
        head.appendChild(value);

        const input = document.createElement("input");
        input.type = "range";
        input.min = String(min);
        input.max = String(max);
        input.step = String(step);
        input.value = String(CONFIG[key]);
        input.dataset.key = key;

        input.addEventListener("input", () => {
            CONFIG[key] = Math.max(min, Math.min(max, Number(input.value)));
            value.textContent = format(CONFIG[key]);
            saveSettings();
            clearScoreCache();
            scan();
        });

        row.appendChild(head);
        row.appendChild(input);
        panel.appendChild(row);

        return row;
    }

    function intRow(panel, { key, label, min, max, step }) {
        const row = document.createElement("label");
        row.className = "yt-ai-row";

        const head = document.createElement("div");
        head.className = "yt-ai-row-head";

        const name = document.createElement("span");
        name.textContent = label;

        const input = document.createElement("input");
        input.type = "number";
        input.className = "yt-ai-num";
        input.min = String(min);
        input.max = String(max);
        input.step = String(step);
        input.value = String(CONFIG[key]);
        input.dataset.key = key;

        input.addEventListener("change", () => {
            let value = Number(input.value);

            if (!Number.isFinite(value)) {
                input.value = String(CONFIG[key]);
                return;
            }

            value = Math.max(min, Math.min(max, value));
            CONFIG[key] = value;
            input.value = String(value);
            saveSettings();
            clearScoreCache();
            scan();
        });

        head.appendChild(name);
        head.appendChild(input);
        row.appendChild(head);
        panel.appendChild(row);

        return row;
    }

    function checkRow(panel, { key, label }) {
        const row = document.createElement("label");
        row.className = "yt-ai-check";

        const input = document.createElement("input");
        input.type = "checkbox";
        input.checked = CONFIG[key] !== false;
        input.dataset.key = key;

        input.addEventListener("change", () => {
            CONFIG[key] = input.checked;
            saveSettings();
            scan();
        });

        const name = document.createElement("span");
        name.textContent = label;

        row.appendChild(input);
        row.appendChild(name);
        panel.appendChild(row);

        return row;
    }

    function urlRow(panel, { key, label, placeholder }) {
        const row = document.createElement("label");
        row.className = "yt-ai-row";

        const name = document.createElement("div");
        name.className = "yt-ai-row-head";
        name.textContent = label;

        const input = document.createElement("input");
        input.type = "url";
        input.className = "yt-ai-url";
        input.placeholder = placeholder || "";
        input.value = CONFIG[key] || "";
        input.dataset.key = key;

        input.addEventListener("change", () => {
            CONFIG[key] = String(input.value || "").trim();
            saveSettings();
            fetchRemoteLexicons();
        });

        row.appendChild(name);
        row.appendChild(input);
        panel.appendChild(row);

        return row;
    }

    function sectionTitle(panel, text) {
        const title = document.createElement("div");
        title.className = "yt-ai-section";
        title.textContent = text;
        panel.appendChild(title);
    }

    function buildSettingsPanel() {
        if (document.querySelector("#yt-ai-score-panel")) {
            return document.querySelector("#yt-ai-score-panel");
        }

        const panel = document.createElement("div");
        panel.id = "yt-ai-score-panel";
        panel.hidden = true;

        const header = document.createElement("div");
        header.className = "yt-ai-panel-head";
        header.innerHTML = "<strong>YT AI Score — thresholds</strong><span>v" + VERSION + "</span>";
        panel.appendChild(header);

        sectionTitle(panel, "Tolerância");
        sliderRow(panel, { key: "minimumScoreToShow", label: "AI Ocultar por Score", min: 0, max: 1, step: 0.05, percent: true });
        sliderRow(panel, { key: "minimumAutomationToShow", label: "Automação Ocultar por Score", min: 0, max: 1, step: 0.05, percent: true });
        sliderRow(panel, { key: "minimumClickbaitToShow", label: "Clickbait Ocultar por Score", min: 0, max: 1, step: 0.05, percent: true });

        const hiddenLine = document.createElement("div");
        hiddenLine.className = "yt-ai-row-head";

        const hiddenStatus = document.createElement("span");
        hiddenStatus.id = "yt-ai-hidden-status";
        hiddenStatus.className = "yt-ai-val";
        hiddenStatus.textContent =
            `${scanStats.hidden} ocultos de ${scanStats.evaluated} avaliados`;

        hiddenLine.appendChild(hiddenStatus);
        panel.appendChild(hiddenLine);

        sectionTitle(panel, "Visibilidade");
        checkRow(panel, { key: "showAI", label: "Mostrar IA" });
        checkRow(panel, { key: "showAutomation", label: "Mostrar automação" });
        checkRow(panel, { key: "showClickbait", label: "Mostrar BAIT" });

        /*
         * FUTURO (ajuste fino): faixas de cor dos badges.
         * sectionTitle(panel, "Faixas de cor (low / med / high)");
         * sliderRow(panel, { key: "lowThreshold", ... });
         * sliderRow(panel, { key: "mediumThreshold", ... });
         * sliderRow(panel, { key: "highThreshold", ... });
         */

        /*
         * FUTURO (ajuste fino): expor pesos internos do scoring.
         * Hoje o menu mostra só thresholds baseados na pontuação
         * visível (AI/AUTO/CLICK 0–100 e faixas de cor).
         *
         * sectionTitle(panel, "Pesos IA / Automação");
         * sliderRow(panel, { key: "titleWeight", ... });
         * sliderRow(panel, { key: "titleCap", ... });
         * sliderRow(panel, { key: "channelWeight", ... });
         * sliderRow(panel, { key: "channelCap", ... });
         * sliderRow(panel, { key: "bodyWeight", ... });
         * sliderRow(panel, { key: "bodyCap", ... });
         * sliderRow(panel, { key: "automationPerMatch", ... });
         * sliderRow(panel, { key: "automationBonus", ... });
         *
         * sectionTitle(panel, "Clickbait");
         * intRow(panel, { key: "clickbaitPointsNeeded", ... });
         * intRow(panel, { key: "longTitleLen", ... });
         *
         * sectionTitle(panel, "Pesos dos léxicos");
         * sliderRow(panel, { key: "remoteWeight", ... });
         * sliderRow(panel, { key: "remoteCap", ... });
         * sliderRow(panel, { key: "aiRemoteWeight", ... });
         * sliderRow(panel, { key: "aiRemoteCap", ... });
         * sliderRow(panel, { key: "autoRemoteWeight", ... });
         * sliderRow(panel, { key: "autoRemoteCap", ... });
         */

        sectionTitle(panel, "Léxicos remotos (git via HTTP)");
        checkRow(panel, { key: "lexiconAutoUpdate", label: "Atualizar léxicos ao iniciar" });
        urlRow(panel, {
            key: "lexiconClickbaitUrl",
            label: "URL clickbait (data/clickbait_br.json)",
            placeholder: "https://raw.githubusercontent.com/darocaecobr/lexico-filter/refs/heads/main/data/clickbait_br.json",
        });
        urlRow(panel, {
            key: "lexiconAiUrl",
            label: "URL IA (data/ai_br.json)",
            placeholder: "https://raw.githubusercontent.com/darocaecobr/lexico-filter/refs/heads/main/data/ai_br.json",
        });
        urlRow(panel, {
            key: "lexiconAutomationUrl",
            label: "URL automação (data/automation_br.json)",
            placeholder: "https://raw.githubusercontent.com/darocaecobr/lexico-filter/refs/heads/main/data/automation_br.json",
        });

        for (const kind of LEXICON_KINDS) {
            const line = document.createElement("div");
            line.className = "yt-ai-row-head";

            const status = document.createElement("span");
            status.id = `yt-ai-lexicon-status-${kind}`;
            status.className = "yt-ai-val";
            status.textContent = `${kind}: ${lexicons[kind].status}`;

            line.appendChild(status);
            panel.appendChild(line);
        }

        const lexRow = document.createElement("div");
        lexRow.className = "yt-ai-row-head";

        const lexReload = document.createElement("button");
        lexReload.type = "button";
        lexReload.className = "yt-ai-mini";
        lexReload.textContent = "Recarregar léxicos";
        lexReload.addEventListener("click", () => {
            saveSettings();
            fetchRemoteLexicons();
        });

        lexRow.appendChild(lexReload);
        panel.appendChild(lexRow);

        const footer = document.createElement("div");
        footer.className = "yt-ai-footer";

        const reset = document.createElement("button");
        reset.type = "button";
        reset.textContent = "Resetar padrões";
        reset.addEventListener("click", () => {
            Object.assign(CONFIG, { ...DEFAULTS });
            saveSettings();
            clearScoreCache();
            panel.remove();
            buildSettingsPanel().hidden = false;
            scan();
        });

        const close = document.createElement("button");
        close.type = "button";
        close.textContent = "Fechar";
        close.addEventListener("click", () => {
            panel.hidden = true;
        });

        footer.appendChild(reset);
        footer.appendChild(close);
        panel.appendChild(footer);

        const hint = document.createElement("div");
        hint.className = "yt-ai-hint";
        hint.textContent = "Léxicos BR: data/{clickbait,ai,automation}_br.json (scripts/mine_br_lexicon.py --kind ...). URLs padrão: darocaecobr/lexico-filter (raw). Use Recarregar após editar. Mudanças limpam o cache e reavaliam os cards.";
        panel.appendChild(hint);

        document.body.appendChild(panel);

        return panel;
    }

    function addSettingsButton() {
        if (
            document.querySelector(
                "#yt-ai-score-settings"
            )
        ) {
            return;
        }

        const button =
            document.createElement("button");

        button.id =
            "yt-ai-score-settings";

        button.type = "button";
        button.textContent = "YTAI ⚙";
        button.title = "Editar thresholds (YT AI Score)";

        const toggle = (event) => {
            event.stopPropagation();
            const panel = buildSettingsPanel();
            panel.hidden = !panel.hidden;
        };

        button.addEventListener("click", toggle);

        document.addEventListener("click", (event) => {
            const panel = document.querySelector("#yt-ai-score-panel");

            if (!panel || panel.hidden) {
                return;
            }

            if (
                panel.contains(event.target) ||
                button.contains(event.target)
            ) {
                return;
            }

            panel.hidden = true;
        });

        document.addEventListener("keydown", (event) => {
            if (event.key === "Escape") {
                document.querySelector("#yt-ai-score-panel")?.setAttribute("hidden", "");
            }
        });

        if (typeof GM_registerMenuCommand === "function") {
            try {
                GM_registerMenuCommand("YT AI Score: abrir thresholds", () => {
                    buildSettingsPanel().hidden = false;
                });
                GM_registerMenuCommand("YT AI Score: resetar padrões", () => {
                    Object.assign(CONFIG, { ...DEFAULTS });
                    saveSettings();
                    clearScoreCache();
                    scan();
                });
            } catch {
                // Ignore TM menu errors.
            }
        }

        document.body.appendChild(
            button
        );
    }

    GM_addStyle(`
        .yt-ai-score-wrapper {
            position: absolute !important;
            top: 6px;
            right: 6px;

            display: flex;
            flex-direction: column;
            gap: 3px;

            z-index: 9999;
            pointer-events: auto;
        }

        .yt-ai-score {
            display: block;

            width: max-content;

            padding: 3px 6px;

            border-radius: 4px;

            background: rgba(0, 0, 0, 0.82);
            color: #fff;

            font-family: Arial, sans-serif;
            font-size: 10px;
            font-weight: 700;

            line-height: 1.2;

            box-sizing: border-box;
        }

        .yt-ai-low {
            opacity: 0.65;
        }

        .yt-ai-medium {
            opacity: 0.85;
        }

        .yt-ai-high {
            font-weight: 800;
        }

        .yt-ai-very-high {
            font-size: 11px;
            font-weight: 900;
        }

        #yt-ai-score-settings {
            position: fixed;
            right: 16px;
            bottom: 16px;

            z-index: 999999;

            border: 1px solid rgba(255,255,255,.2);
            border-radius: 6px;

            padding: 8px 12px;

            background: #111;
            color: #fff;

            font-size: 12px;
            font-weight: 700;

            cursor: pointer;
        }

        #yt-ai-score-panel {
            position: fixed;
            right: 16px;
            bottom: 56px;

            width: 300px;
            max-height: 70vh;
            overflow-y: auto;

            z-index: 1000000;

            border: 1px solid rgba(255,255,255,.2);
            border-radius: 10px;

            padding: 12px;

            background: rgba(17,17,17,.97);
            color: #fff;

            font-family: Arial, sans-serif;
            font-size: 12px;

            box-shadow: 0 8px 32px rgba(0,0,0,.5);
        }

        #yt-ai-score-panel[hidden] {
            display: none;
        }

        .yt-ai-panel-head {
            display: flex;
            justify-content: space-between;
            align-items: baseline;

            margin-bottom: 8px;
        }

        .yt-ai-section {
            margin: 10px 0 6px;

            font-weight: 800;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: .04em;
            opacity: .8;
        }

        .yt-ai-row {
            display: block;
            margin-bottom: 8px;
        }

        .yt-ai-row-head {
            display: flex;
            justify-content: space-between;
            align-items: center;
            gap: 8px;

            margin-bottom: 4px;
        }

        .yt-ai-val {
            font-variant-numeric: tabular-nums;
            opacity: .85;
        }

        .yt-ai-row input[type="range"] {
            width: 100%;
        }

        .yt-ai-num {
            width: 70px;
            padding: 2px 6px;

            border-radius: 4px;
            border: 1px solid rgba(255,255,255,.2);

            background: #222;
            color: #fff;
        }

        .yt-ai-url {
            width: 100%;
            padding: 4px 6px;

            border-radius: 4px;
            border: 1px solid rgba(255,255,255,.2);

            background: #222;
            color: #fff;

            font-size: 11px;
            box-sizing: border-box;
        }

        .yt-ai-mini {
            border: 1px solid rgba(255,255,255,.2);
            border-radius: 6px;

            padding: 4px 8px;

            background: #222;
            color: #fff;

            font-size: 11px;
            font-weight: 700;

            cursor: pointer;
        }
        .yt-ai-check {
            display: flex;
            gap: 8px;
            align-items: center;

            margin-bottom: 6px;
            cursor: pointer;
        }

        .yt-ai-footer {
            display: flex;
            gap: 8px;
            margin-top: 10px;
        }

        .yt-ai-footer button {
            flex: 1;

            border: 1px solid rgba(255,255,255,.2);
            border-radius: 6px;

            padding: 6px;

            background: #222;
            color: #fff;

            font-size: 12px;
            font-weight: 700;

            cursor: pointer;
        }

        .yt-ai-hint {
            margin-top: 8px;

            font-size: 10px;
            line-height: 1.4;
            opacity: .7;
        }
    `);

    function init() {
        addSettingsButton();
        loadLexiconCache();
        scan();

        if (CONFIG.lexiconAutoUpdate &&
            (CONFIG.lexiconClickbaitUrl || CONFIG.lexiconAiUrl || CONFIG.lexiconAutomationUrl)) {
            fetchRemoteLexicons();
        }

        observer.observe(
            document.body,
            {
                childList: true,
                subtree: true
            }
        );

        setInterval(
            scan,
            RESCAN_MS
        );

        log(
            `YouTube AI Score ${VERSION} iniciado`
        );
    }

    if (
        document.readyState === "loading"
    ) {
        document.addEventListener(
            "DOMContentLoaded",
            init,
            { once: true }
        );
    } else {
        init();
    }
})();
